#docker-compose.yml
version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '8501:8501'
    environment:
      - BACKEND_URL=http://backend:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./frontend:/app
      - ./frontend/.streamlit:/app/.streamlit

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NVIDIA_API_KEY=${NVIDIA_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
